using System.Collections.Generic;

namespace Wolverine.Models.GraphTheory
{
    /// <summary>
    /// Represents a fastest path table generated by Dijkstra's Algorithm
    /// </summary>
    public class FastestPathTable
    {
        #region Constructors

        /// <summary>
        /// Default constructor
        /// </summary>
        public FastestPathTable()
        {
            Rows = new List<FastestPathRow>();
        }

        #endregion

        #region Public Properties

        /// <summary>
        /// The primary node's id
        /// </summary>
        public string PrimaryNodeId { get; set; }

        /// <summary>
        /// The rows of the fastest path table
        /// </summary>
        public List<FastestPathRow> Rows { get; set; }

        #endregion
    }
}
