//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wolverine.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessageKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessageKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wolverine.Models.Resources.ErrorMessageKeys", typeof(ErrorMessageKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_BLANK_NODE_ID.
        /// </summary>
        public static string ERROR_BLANK_NODE_ID {
            get {
                return ResourceManager.GetString("ERROR_BLANK_NODE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_DUPLICATE_MAZE_CELL_ID.
        /// </summary>
        public static string ERROR_DUPLICATE_MAZE_CELL_ID {
            get {
                return ResourceManager.GetString("ERROR_DUPLICATE_MAZE_CELL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_DUPLICATE_NEIGHBOR_NODE_ID.
        /// </summary>
        public static string ERROR_DUPLICATE_NEIGHBOR_NODE_ID {
            get {
                return ResourceManager.GetString("ERROR_DUPLICATE_NEIGHBOR_NODE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_DUPLICATE_NODE_ID.
        /// </summary>
        public static string ERROR_DUPLICATE_NODE_ID {
            get {
                return ResourceManager.GetString("ERROR_DUPLICATE_NODE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_INVALID_DIMENSIONS.
        /// </summary>
        public static string ERROR_INVALID_DIMENSIONS {
            get {
                return ResourceManager.GetString("ERROR_INVALID_DIMENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_INVALID_DIRECTION.
        /// </summary>
        public static string ERROR_INVALID_DIRECTION {
            get {
                return ResourceManager.GetString("ERROR_INVALID_DIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_NODE_ID_NOT_FOUND_IN_COLLECTION.
        /// </summary>
        public static string ERROR_NODE_ID_NOT_FOUND_IN_COLLECTION {
            get {
                return ResourceManager.GetString("ERROR_NODE_ID_NOT_FOUND_IN_COLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_UNMATCHING_EDGE_COSTS.
        /// </summary>
        public static string ERROR_UNMATCHING_EDGE_COSTS {
            get {
                return ResourceManager.GetString("ERROR_UNMATCHING_EDGE_COSTS", resourceCulture);
            }
        }
    }
}
